version: '3.8'

services:
  mlevaluacion:
    build: .
    image: daplaza/mlevaluacion:latest
    container_name: mlevaluacion
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./mlruns:/app/mlruns
      - ./reports:/app/reports
    environment:
      - PYTHONUNBUFFERED=1