channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=25.0.1
- pip:
  - mlflow==2.8.1
  - cloudpickle==2.2.1
  - numpy==1.24.3
  - packaging==23.2
  - psutil==7.0.0
  - pyyaml==6.0.2
  - scikit-learn==1.3.0
  - scipy==1.15.2
name: mlflow-env
